language: node_js
node_js:
  - lts/*
install:
  - yarn install # npm ci
script:
  - yarn docs:build # npm run docs:build
after_success:
  - echo 'leetcode.ytxcloud.com' > CNAME
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  target_branch: gh-pages
  github_token: $TRAVIS_GITHUB_TOKEN # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面进行配置，设置为 secure variable
  keep_history: true
  on:
    branch: master
notifications:
  email: false